name: Playwright Tests
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
      
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    
    # - name: Run Playwright tests
    #   run: npx playwright test --reporter=json > results.json || true

    - name: Download file into results.json
      # run: wget -O results.json "https://drive.google.com/file/d/1P62Imc10TNg5O0OO06UR8T0VuyBJYYWV/view?usp=sharing"
      run: wget -O results.json --no-check-certificate "https://docs.google.com/uc?export=download&confirm=t&id=1P62Imc10TNg5O0OO06UR8T0VuyBJYYWV" 


    - name: Install processor deps
      run: |
        cd .github/workflows/actions/processor
        npm install
      
    - name: Upload results to MySQL
      uses: ./.github/workflows/actions/processor
      with:
        results-file: results.json
        db-host: 'serverless-northeurope.sysp0000.db3.skysql.com'
        db-user: 'dbpbf33147723'
        db-pass: '4bPgtnNrIo7.E0JhyWomS5Nu'
        db-name: 'willybot'
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Playwright results
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: results.json


    - name: Send Slack notification
      if: always() 
      uses: slackapi/slack-github-action@v1.27.0
      with:
        channel-id: 'C09FYPLJA1W'
        slack-message: |
         Playwright Tests 
         Status: ${{ job.status }} 
         Download full report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
              
      env:
        SLACK_BOT_TOKEN: ${{ secrets.BOTUSEROAUTHTOKEN }}
